config/routes.rb
Rails.application.routes.draw do

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'student_password', to: 'students#password', as:'student_password'
  get 'parent_password', to: 'parents#password', as:'parent_password'

  resources :sessions

  resources :grades

  resources :assignments

  resources :subjects

  resources :students

  resources :parents

  resources :teachers

  root 'sessions#new'

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_secure_password
  has_many :students, dependent: :destroy
  has_many :grades
  has_many :assignments
  accepts_nested_attributes_for :students
  accepts_nested_attributes_for :grades
  accepts_nested_attributes_for :assignments
  validates :email, uniqueness: true
  validates :name, presence: true


end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  # before_action :permission?, except: [:index]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
    @teacher = Teacher.new
    @parents = Parent.all
    @student = Student.new
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to root_path, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to root_path, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :email, :password, :password_confirmation, student_attributes: [:id, :name])
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<%= link_to 'New Teacher', new_teacher_path %> |
<%= link_to 'New Parent/Student', new_parent_path %> |
<%= link_to 'New Assignment', new_assignment_path %> |
<h1>Teachers</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.email %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Delete', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Students</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Assignment</th>
        <th>Grade</th>
        <th>Parent</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% current_user.students.each do |s| %>
        <% s.grades.each do |g| %>
          <tr>
            <td><%= s.name %></td>
            <td><%= s.email %></td>
            <td><%= g.assignment.name %></td>
            <td><%= g.score %></td>
            <td><%= s.parent.name%></td>
            <td><%= link_to 'Edit student', edit_student_path(s) %></td>
            <td><%= link_to 'Edit Assignment', edit_assignment_path(g.assignment) %></td>
            <td><%= link_to 'Delete', s, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<h1>Parents</h1>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% current_user.students.each do |s| %>
            <tr>
              <td><%= s.parent.name %></td>
              <td><%= s.parent.email %></td>
              <td><%= link_to 'Edit', edit_parent_path(s.parent) %></td>
              <td><%= link_to 'Delete', s.parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
<br>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<% if @teacher.students.any? %>
  <h2> Assignments and Grades </h2>
  <ul>
    <% @teacher.students.each do |s| %>
      <h3><%= s.name %></h3>
      <% s.grades.each do |grade| %>

        <li><%= grade.assignment.name %>:       <%= grade.score %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>